version: '3.8'

services:
  # Graph Database
  neo4j:
    image: neo4j:5.15-community
    container_name: codex-fabric-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/codexfabric
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - codex-fabric-network

  # Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: codex-fabric-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - codex-fabric-network

  # Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: codex-fabric-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codex-fabric-network

  # Metadata Database
  postgres:
    image: postgres:15-alpine
    container_name: codex-fabric-postgres
    environment:
      - POSTGRES_DB=codexfabric
      - POSTGRES_USER=codexfabric
      - POSTGRES_PASSWORD=codexfabric
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codex-fabric-network

  # Main API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codex-fabric-api
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=codexfabric
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://codexfabric:codexfabric@postgres:5432/codexfabric
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    depends_on:
      - neo4j
      - qdrant
      - redis
      - postgres
    networks:
      - codex-fabric-network

  # Web UI
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: codex-fabric-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - codex-fabric-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  qdrant_data:
  redis_data:
  postgres_data:

networks:
  codex-fabric-network:
    driver: bridge 